/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner;
import Business.Plane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gaorong
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private Airliner aln;
    public ViewJPanel(Airliner aln) {
        initComponents();
        this.aln = aln;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTakeoffTime = new javax.swing.JTextField();
        btnExpired = new javax.swing.JCheckBox();
        btnItIsAvailable = new javax.swing.JCheckBox();
        btnUnavailable = new javax.swing.JCheckBox();
        btnVaild = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtAirport = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSerialNum = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSeatsNum = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtManufact = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtManYear = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Skia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("View Airplane Information");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Serial Number", "Model Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel6.setText("Take-off time:");

        txtTakeoffTime.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtTakeoffTime.setForeground(new java.awt.Color(204, 51, 0));

        buttonGroup1.add(btnExpired);
        btnExpired.setFont(new java.awt.Font("Al Bayan", 1, 13)); // NOI18N
        btnExpired.setText("Expired");

        buttonGroup2.add(btnItIsAvailable);
        btnItIsAvailable.setFont(new java.awt.Font("Al Bayan", 1, 13)); // NOI18N
        btnItIsAvailable.setText("Available");
        btnItIsAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItIsAvailableActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnUnavailable);
        btnUnavailable.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnUnavailable.setText("Unavailable");

        buttonGroup1.add(btnVaild);
        btnVaild.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnVaild.setText("Vaild");
        btnVaild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaildActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel14.setText("Airport:");

        txtAirport.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtAirport.setForeground(new java.awt.Color(204, 51, 0));

        jLabel15.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel15.setText("Serial Number:");

        txtSerialNum.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtSerialNum.setForeground(new java.awt.Color(204, 51, 0));

        jLabel16.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel16.setText("Model Number:");

        txtModelNum.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtModelNum.setForeground(new java.awt.Color(204, 51, 0));

        jLabel17.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel17.setText("Seats Number:");

        txtSeatsNum.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtSeatsNum.setForeground(new java.awt.Color(204, 51, 0));

        jLabel18.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel18.setText("Manufacturer:");

        txtManufact.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtManufact.setForeground(new java.awt.Color(204, 51, 0));

        jLabel19.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel19.setText("Manufacture Year:");

        txtManYear.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        txtManYear.setForeground(new java.awt.Color(204, 51, 0));

        jLabel20.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel20.setText("Maintenance Certificate:");

        jLabel21.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel21.setText("Available:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnExpired)
                            .addGap(28, 28, 28)
                            .addComponent(btnVaild))
                        .addComponent(txtTakeoffTime)
                        .addComponent(txtAirport)
                        .addComponent(txtSerialNum)
                        .addComponent(txtModelNum)
                        .addComponent(txtSeatsNum)
                        .addComponent(txtManufact)
                        .addComponent(txtManYear, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnItIsAvailable)
                        .addGap(18, 18, 18)
                        .addComponent(btnUnavailable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnViewDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTakeoffTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtSeatsNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtManufact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtManYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(btnExpired)
                            .addComponent(btnVaild))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(btnItIsAvailable)
                            .addComponent(btnUnavailable)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVaildActionPerformed

    private void btnItIsAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItIsAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnItIsAvailableActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedrow =jTable1.getSelectedRow();
        
        if(selectedrow >=0)
        {
            Plane p = (Plane)jTable1.getValueAt(selectedrow, 0);
            txtAirport.setText(p.getSchedule().getAirport());
            txtManYear.setText(p.getYear());
            txtManufact.setText(p.getManufacture());
            txtModelNum.setText(p.getModelNumber());
            txtSeatsNum.setText((p.getSeatsNumber()+""));
            txtSerialNum.setText(p.getSerialNumber());
            txtTakeoffTime.setText(p.getSchedule().getTakeOffTime());
            if(p.getSchedule().getIsavailable())
                btnItIsAvailable.setSelected(true);
            else
                btnUnavailable.setSelected(true);
            
            if(p.getIsExpired())
                btnExpired.setSelected(true);
            else
                btnVaild.setSelected(true);
        }
        else
           JOptionPane.showMessageDialog(null,"Plesase select any row");
                // TODO add your handling code here:
                                     
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedrow =jTable1.getSelectedRow();
        
        if(selectedrow >=0)
        {
            Plane p = (Plane)jTable1.getValueAt(selectedrow, 0);
            int i = aln.getAirliner().indexOf(p);
            EditJFrame ef = new EditJFrame(aln,i);
            ef.setDefaultCloseOperation(EditJFrame.DISPOSE_ON_CLOSE);
            ef.setVisible(true);
            jTable1.setValueAt(p, selectedrow, 0);
            ef.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e) {
                  populateTable();
            }
            });
        }
        else
           JOptionPane.showMessageDialog(null,"Plesase select any row");
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JCheckBox btnExpired;
    private javax.swing.JCheckBox btnItIsAvailable;
    private javax.swing.JCheckBox btnUnavailable;
    private javax.swing.JCheckBox btnVaild;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAirport;
    private javax.swing.JTextField txtManYear;
    private javax.swing.JTextField txtManufact;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtSeatsNum;
    private javax.swing.JTextField txtSerialNum;
    private javax.swing.JTextField txtTakeoffTime;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        
        
        for(Plane pl : aln.getAirliner())
        {
            Object row[] = new Object[2];
            row[0] = pl;
            row[1] = pl.getModelNumber();
            dtm.addRow(row);
            
        }
    }
}
