/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Salesman;

import Business.business;
import Business.customer;
import Business.market;
import Business.market_list;
import Business.person;
import Business.sales_person;
import Interface.LoginJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Yin
 */
public class salesmanWelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form salemanWelcomePanel
     */
    JPanel upc;
    business b;
    sales_person s;
    
    public salesmanWelcomePanel(JPanel upc, business b, person p) {
        initComponents();
        this.upc = upc;
        this.b = b;
        this.s = (sales_person) p;
        
//加载 custCombo
        for(market m: b.getMl().getMa()){
            for(customer c: m.getCa()){
                custCombo.addItem(c.getName());
            }            
        }        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        custCombo = new javax.swing.JComboBox<>();
        serveCustomerBtn = new javax.swing.JButton();
        serveCustomerBtn1 = new javax.swing.JButton();
        serveCustomerBtn2 = new javax.swing.JButton();
        serveCustomerBtn3 = new javax.swing.JButton();

        jLabel1.setText("Customer Name: ");

        custCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custComboActionPerformed(evt);
            }
        });

        serveCustomerBtn.setText("Serve Customer");
        serveCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerBtnActionPerformed(evt);
            }
        });

        serveCustomerBtn1.setText("LogOut");
        serveCustomerBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerBtn1ActionPerformed(evt);
            }
        });

        serveCustomerBtn2.setText("Customers you ever served");
        serveCustomerBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerBtn2ActionPerformed(evt);
            }
        });

        serveCustomerBtn3.setText("Review all your order");
        serveCustomerBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCustomerBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serveCustomerBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(serveCustomerBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(serveCustomerBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serveCustomerBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(custCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serveCustomerBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(serveCustomerBtn1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(serveCustomerBtn3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(serveCustomerBtn2)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void custComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custComboActionPerformed

    private void serveCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerBtnActionPerformed
        // TODO add your handling code here:
         String custName = custCombo.getSelectedItem().toString();
         market_list ml = b.getMl();
            customer c = ml.findCustomerByName(custName);
            market m = ml.findMarketByCustomerName(custName);
         
         serveCustomerPanel panel = new serveCustomerPanel(upc,b,s,m,c);
         upc.add("serveCustomerPanel",panel);
         CardLayout layout = (CardLayout) upc.getLayout();
         layout.next(upc);

    }//GEN-LAST:event_serveCustomerBtnActionPerformed

    private void serveCustomerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerBtn1ActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        //加载上一个component，并且使用它的刷新表格方法

        Component[] componentArray = upc.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LoginJPanel lp =  (LoginJPanel) component;
        lp.clearText();
       
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_serveCustomerBtn1ActionPerformed

    private void serveCustomerBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerBtn2ActionPerformed
        // TODO add your handling code here:
         reviewCustomerRankPanel panel = new reviewCustomerRankPanel(upc,b,s);
         upc.add("reviewCustomerRankPanel",panel);
         CardLayout layout = (CardLayout) upc.getLayout();
         layout.next(upc);
        
    }//GEN-LAST:event_serveCustomerBtn2ActionPerformed

    private void serveCustomerBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCustomerBtn3ActionPerformed
        // TODO add your handling code here:
        
        reviewOrdersPanel panel = new reviewOrdersPanel(upc,b,s);
         upc.add("reviewOrdersPanel",panel);
         CardLayout layout = (CardLayout) upc.getLayout();
         layout.next(upc);
    }//GEN-LAST:event_serveCustomerBtn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> custCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton serveCustomerBtn;
    private javax.swing.JButton serveCustomerBtn1;
    private javax.swing.JButton serveCustomerBtn2;
    private javax.swing.JButton serveCustomerBtn3;
    // End of variables declaration//GEN-END:variables
}
