/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Profile.Address;
import Profile.CreditCard;
import Profile.FinancialAcc;
import Profile.LicenseData;
import Profile.Person;

import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.*;
import java.io.*;
import java.util.Enumeration;
import javax.swing.*;
/**
 *
 * @author Rong gao
 */
public class CreateJPanel extends javax.swing.JPanel {
    private Person person;
    private Address address;
    private FinancialAcc financialAcc;
    private CreditCard creditCard;
    private LicenseData licenseData;
    //private ViewJPanel vp;
    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        person = new Person();
        address = new Address();
        financialAcc = new FinancialAcc();
        creditCard = new CreditCard();
        licenseData = new LicenseData();        
        initComponents();
    }

    public Person getPerson(){
        return this.person;
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        activeGroup = new javax.swing.ButtonGroup();
        personPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        picPanel = new javax.swing.JPanel();
        picLabel = new javax.swing.JLabel();
        browse = new java.awt.Button();
        addressPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        countryText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        zipCodeText = new javax.swing.JTextField();
        financialAccPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        accNumText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        savingRadio = new javax.swing.JRadioButton();
        checkingRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        debtText = new javax.swing.JTextField();
        creditText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        activeRadio = new javax.swing.JRadioButton();
        noActiveRadio = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        creationDateText = new javax.swing.JTextField();
        creditCardPanel = new javax.swing.JPanel();
        credCardText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        credDoeText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        credLineText = new javax.swing.JTextField();
        nameofCardText = new javax.swing.JTextField();
        bankText = new javax.swing.JTextField();
        licenseDataPanel = new javax.swing.JPanel();
        licNumText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        licDobText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        licStateText = new javax.swing.JTextField();
        doeText = new javax.swing.JTextField();
        doiText = new javax.swing.JTextField();
        submit = new javax.swing.JButton();

        personPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Person"));

        jLabel16.setText("First Name:");

        firstNameText.setToolTipText("");
        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        jLabel18.setText("Last Name:");

        lastNameText.setToolTipText("");
        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        picPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Picture"));
        picPanel.setToolTipText("");

        javax.swing.GroupLayout picPanelLayout = new javax.swing.GroupLayout(picPanel);
        picPanel.setLayout(picPanelLayout);
        picPanelLayout.setHorizontalGroup(
            picPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        picPanelLayout.setVerticalGroup(
            picPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );

        browse.setLabel("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personPanelLayout = new javax.swing.GroupLayout(personPanel);
        personPanel.setLayout(personPanelLayout);
        personPanelLayout.setHorizontalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(30, 30, 30)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(picPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(browse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        personPanelLayout.setVerticalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(picPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(browse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        addressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));

        jLabel19.setText("Country:");

        countryText.setToolTipText("");
        countryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextActionPerformed(evt);
            }
        });

        jLabel20.setText("City:");
        jLabel20.setPreferredSize(new java.awt.Dimension(48, 15));

        jLabel21.setText("State:");
        jLabel21.setPreferredSize(new java.awt.Dimension(48, 15));

        stateText.setToolTipText("");
        stateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextActionPerformed(evt);
            }
        });

        cityText.setToolTipText("");
        cityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextActionPerformed(evt);
            }
        });

        jLabel22.setText("Street:");

        streetText.setToolTipText("");
        streetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTextActionPerformed(evt);
            }
        });

        jLabel23.setText("ZipCode:");

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(30, 30, 30)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cityText)
                    .addComponent(countryText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetText)
                    .addComponent(zipCodeText, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap())
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(20, 20, 20)
                .addGroup(addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(zipCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        financialAccPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Financial Account"));
        financialAccPanel.setPreferredSize(new java.awt.Dimension(350, 289));

        jLabel2.setText("Account Number:");

        accNumText.setPreferredSize(new java.awt.Dimension(21, 21));
        accNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNumTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Debt:");
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 15));

        typeGroup.add(savingRadio);
        savingRadio.setText("Saving");
        savingRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingRadioActionPerformed(evt);
            }
        });

        typeGroup.add(checkingRadio);
        checkingRadio.setText("Checking");
        checkingRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingRadioActionPerformed(evt);
            }
        });

        jLabel1.setText("Account Types:");

        jLabel3.setText("Credit:");
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 15));

        debtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debtTextActionPerformed(evt);
            }
        });

        creditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditTextActionPerformed(evt);
            }
        });

        jLabel17.setText("Active Status:");

        activeGroup.add(activeRadio);
        activeRadio.setText("Active");
        activeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeRadioActionPerformed(evt);
            }
        });

        activeGroup.add(noActiveRadio);
        noActiveRadio.setText("Not Active");
        noActiveRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActiveRadioActionPerformed(evt);
            }
        });

        jLabel24.setText("Creation Date:");

        creationDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creationDateTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout financialAccPanelLayout = new javax.swing.GroupLayout(financialAccPanel);
        financialAccPanel.setLayout(financialAccPanelLayout);
        financialAccPanelLayout.setHorizontalGroup(
            financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financialAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(financialAccPanelLayout.createSequentialGroup()
                        .addComponent(savingRadio)
                        .addGap(20, 20, 20)
                        .addComponent(checkingRadio))
                    .addGroup(financialAccPanelLayout.createSequentialGroup()
                        .addComponent(activeRadio)
                        .addGap(24, 24, 24)
                        .addComponent(noActiveRadio))
                    .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(accNumText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(creditText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(debtText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(creationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        financialAccPanelLayout.setVerticalGroup(
            financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financialAccPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(savingRadio)
                    .addComponent(checkingRadio))
                .addGap(20, 20, 20)
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noActiveRadio)
                    .addComponent(activeRadio)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20)
                .addGroup(financialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(creationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        creditCardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Credit Card"));

        credCardText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credCardTextActionPerformed(evt);
            }
        });

        jLabel11.setText("Credit Card Number:");

        credDoeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credDoeTextActionPerformed(evt);
            }
        });

        jLabel12.setText("Issuing Bank:");

        jLabel13.setText("Expiration Date:");

        jLabel14.setText("Name On the Card:");

        jLabel15.setText("Credit Line:");

        credLineText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credLineTextActionPerformed(evt);
            }
        });

        nameofCardText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameofCardTextActionPerformed(evt);
            }
        });

        bankText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creditCardPanelLayout = new javax.swing.GroupLayout(creditCardPanel);
        creditCardPanel.setLayout(creditCardPanelLayout);
        creditCardPanelLayout.setHorizontalGroup(
            creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditCardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameofCardText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditCardPanelLayout.createSequentialGroup()
                        .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(68, 68, 68)))
                        .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credCardText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(creditCardPanelLayout.createSequentialGroup()
                        .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(116, 116, 116))
                            .addGroup(creditCardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(68, 68, 68)))
                        .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credDoeText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(credLineText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        creditCardPanelLayout.setVerticalGroup(
            creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditCardPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credCardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nameofCardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credDoeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(creditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(credLineText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        licenseDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("License Data"));
        licenseDataPanel.setToolTipText("");

        licNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licNumTextActionPerformed(evt);
            }
        });

        jLabel6.setText("License Number:");

        licDobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licDobTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Date of Issuing:");

        jLabel8.setText("Date of Birth:");

        jLabel9.setText("Date of Expiration:");

        jLabel10.setText("State:");

        licStateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licStateTextActionPerformed(evt);
            }
        });

        doeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doeTextActionPerformed(evt);
            }
        });

        doiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout licenseDataPanelLayout = new javax.swing.GroupLayout(licenseDataPanel);
        licenseDataPanel.setLayout(licenseDataPanelLayout);
        licenseDataPanelLayout.setHorizontalGroup(
            licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(licenseDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(licenseDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doeText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, licenseDataPanelLayout.createSequentialGroup()
                        .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(licenseDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, licenseDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doiText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(licenseDataPanelLayout.createSequentialGroup()
                        .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(licenseDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(116, 116, 116))
                            .addGroup(licenseDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(68, 68, 68)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licDobText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licStateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        licenseDataPanelLayout.setVerticalGroup(
            licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(licenseDataPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(doeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licDobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(licenseDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(licStateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(financialAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(creditCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(licenseDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(submit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(creditCardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(licenseDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(financialAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(submit))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:
        chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            String name = chooser.getSelectedFile().getPath();
            ImageIcon image = new ImageIcon(name);
            image.setImage(image.getImage().getScaledInstance(picLabel.getWidth(), picLabel.getHeight(),Image.SCALE_DEFAULT ));
            picLabel.setIcon(image);
            person.setImage(image);
        }
    }//GEN-LAST:event_browseActionPerformed

    private void countryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextActionPerformed

    private void stateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextActionPerformed

    private void cityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextActionPerformed

    private void streetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextActionPerformed

    private void accNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNumTextActionPerformed

    private void savingRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingRadioActionPerformed

    private void checkingRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingRadioActionPerformed

    private void debtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debtTextActionPerformed

    private void creditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditTextActionPerformed

    private void activeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeRadioActionPerformed

    private void noActiveRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActiveRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActiveRadioActionPerformed

    private void creationDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creationDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creationDateTextActionPerformed

    private void credCardTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credCardTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credCardTextActionPerformed

    private void credDoeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credDoeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credDoeTextActionPerformed

    private void credLineTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credLineTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credLineTextActionPerformed

    private void nameofCardTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameofCardTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameofCardTextActionPerformed

    private void bankTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankTextActionPerformed

    private void licNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licNumTextActionPerformed

    private void licDobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licDobTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licDobTextActionPerformed

    private void licStateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licStateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licStateTextActionPerformed

    private void doeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doeTextActionPerformed

    private void doiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doiTextActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        person.setfirstName(firstNameText.getText());
        person.setlastName(lastNameText.getText());
        
        address.setCountry(countryText.getText());
        address.setState(stateText.getText());
        address.setCity(cityText.getText());
        address.setStreet(streetText.getText());
        address.setZipCode(zipCodeText.getText());
        
        person.setAddress(address);
        financialAcc.setAccNum(accNumText.getText());
        financialAcc.setCredit(creditText.getText());
        financialAcc.setDebt(debtText.getText());
        financialAcc.setCretionDate(creationDateText.getText());
        Enumeration<AbstractButton> radioBtns=typeGroup.getElements();  
        String type = "";
        while (radioBtns.hasMoreElements()) {  
         AbstractButton btn = radioBtns.nextElement();  
           if(btn.isSelected()){  
             type =btn.getText();  
            break;  
           }  
        } 
        if(type.equals("Saving"))
            financialAcc.setIsSavingAcc(true);
        else if(type.equals("Checking"))
            financialAcc.setIsSavingAcc(false);
        
        String active = "";
        radioBtns=activeGroup.getElements();  
         while (radioBtns.hasMoreElements()) {  
         AbstractButton btn = radioBtns.nextElement();  
           if(btn.isSelected()){  
             active =btn.getText();  
            break;  
           }  
        } 
        
        if(active.equals("Active"))
            financialAcc.setActiveStatus(true);
        else if(type.equals("Not Active"))
            financialAcc.setActiveStatus(false);
        System.out.println("type is "+type);
        System.out.println("active is "+active);
        person.setFinancialAcc(financialAcc);
        
        creditCard.setBank(bankText.getText());
        creditCard.setCardNum(credCardText.getText());
        creditCard.setNameOnCard(nameofCardText.getText());
        creditCard.setExpiration(credDoeText.getText());
        creditCard.setCreditLine(credLineText.getText());
        
        person.setCreditCard(creditCard);
        
        licenseData.setDob(licDobText.getText());
        licenseData.setDoe(doeText.getText());
        licenseData.setDoi(doiText.getText());
        licenseData.setNum(licNumText.getText());
        licenseData.setState(licStateText.getText());
        
        person.setLicenseData(licenseData);
        JPanel jp= new JPanel();
        
        JOptionPane.showMessageDialog(jp, "Submit success", "Success",JOptionPane.WARNING_MESSAGE);  
        
    }//GEN-LAST:event_submitActionPerformed

    private JFileChooser chooser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNumText;
    private javax.swing.ButtonGroup activeGroup;
    private javax.swing.JRadioButton activeRadio;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JTextField bankText;
    private java.awt.Button browse;
    private javax.swing.JRadioButton checkingRadio;
    private javax.swing.JTextField cityText;
    private javax.swing.JTextField countryText;
    private javax.swing.JTextField creationDateText;
    private javax.swing.JTextField credCardText;
    private javax.swing.JTextField credDoeText;
    private javax.swing.JTextField credLineText;
    private javax.swing.JPanel creditCardPanel;
    private javax.swing.JTextField creditText;
    private javax.swing.JTextField debtText;
    private javax.swing.JTextField doeText;
    private javax.swing.JTextField doiText;
    private javax.swing.JPanel financialAccPanel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JTextField licDobText;
    private javax.swing.JTextField licNumText;
    private javax.swing.JTextField licStateText;
    private javax.swing.JPanel licenseDataPanel;
    private javax.swing.JTextField nameofCardText;
    private javax.swing.JRadioButton noActiveRadio;
    private javax.swing.JPanel personPanel;
    private javax.swing.JLabel picLabel;
    private javax.swing.JPanel picPanel;
    private javax.swing.JRadioButton savingRadio;
    private javax.swing.JTextField stateText;
    private javax.swing.JTextField streetText;
    private javax.swing.JButton submit;
    private javax.swing.ButtonGroup typeGroup;
    private javax.swing.JTextField zipCodeText;
    // End of variables declaration//GEN-END:variables
}
