/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ConfigureABusiness;
import Business.business;
import Business.market_offer;
import Business.person;
import Business.salesFunction.order;
import Business.salesFunction.order_item;
import Business.sales_person;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Yin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private business b;
    
    public MainJFrame() {
        initComponents();
        setBounds(500,300,500,400);
        
        b= ConfigureABusiness.Initialize("Xeros");
        
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        LoginJPanel panel=new LoginJPanel(b, userProcessContainer);
        userProcessContainer.add(panel);
        layout.next(userProcessContainer);
        
 //为每个 sales_person 配置订单纪录
        CreateRandomOrder();
    }
    
        public void CreateRandomOrder(){
        
        for(person p: b.getPa()){
           if(p.getClass().getSimpleName().equals("sales_person")){
                sales_person s = (sales_person) p;
                
                int m = (int)(Math.random()*4 +1);  // Order数量限制
                for(int a = 0; a<m; a++){
                    int i = (int)(Math.random()*5 +1);  //Item 数量限制
                    order o = randomOrder(i);
                    s.getOa().add(o);
                }
                
                
            }
        }
    
        }//end create RandomOrder

        
     public order randomOrder(int i){
        order o = new order();
//匹配市场    
        int marketNum = (int)(Math.random()*2);
        String market = b.getMl().getMa().get(marketNum).getName();
        o.setMarket(market);

        
//添加 符合条件的offer 到 arrayList
        ArrayList<market_offer> offerList = new ArrayList();

        for(market_offer mo: b.getMoc().getMarketOfferList()){
            if(mo.getMarket().equals(market))
                offerList.add(mo);
        }
        
        for(int m=0;m<i;m++){
            order_item oi = o.addOrderItem();
            //匹配客户
            int custNumber = (int)(Math.random()*6);
            String customerName = b.getMl().getMa().get(marketNum).getCa().get(custNumber).getName();
            o.setCustomer(customerName);
//从相应市场随机生成offer          
            int offerNumber = (int)(Math.random()*10);
            market_offer mo = offerList.get(offerNumber);
            
            oi.setProduct(mo.getP());
            int quantity = (int)(Math.random()*5+1);
            oi.setQuantity(quantity);
            int actualPrice = randomNum(mo.getFloor(),mo.getCeiling());
            oi.setActualPrice(actualPrice);
            
            o.setTotal_price(o.countTotal());
        }
        
        return o;
    }
    
    public int randomNum(int a,int b){
        
        int min=a;
        int max=b;
        Random random = new Random();
        int s = random.nextInt(max)%(max-min+1) + min;
        System.out.println(s);
        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(userProcessContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
